### ISSUE TITLE
Lekce 5

### ISSUE THREAD

**Issue by maro-create** [maro-create/python-012021#1]
@pesikj 
Predem moc dekuji za kontrolu :-)!

**Comment by pesikj** [comment]
Ahoj Maro,

máš issue v jiném repozitáři než řešení, ale našel jsem je :-)

### Příklad 21

Vyřešené je vše správně, mám pouze dvě formální pozvánky. Máš tam dvakrát `import pandas`, stačí jednou. Plus prosím nepoužívej velké písmeno pro název proměnné. Doporučil bych ti třeba název `max_price` a `min_price`, samotné `max` a `min` není taky úplně nejlepší, protože by se tím překryly funkce  `max` a `min`.

```python

max_price = (akcie['High'].max())
min_price = (akcie['Low'].min())
price_range = max_price - min_price

```

### Příklad 22

Super :-)

### Příklad 23

Taky super :-)

### Příklad 24

Taky super :-)

### Příklad 25

Taky super :-)

### Shrnutí

Máš vše moc pěkně zpracované včetně pokročilých variant a rozšíření, takže připisuji 5 bodů :-)
